import { menuItem } from "./menu-item";

export const menuItems = {
  foods: [
    {
      ...menuItem,
      name: "Classic Burger",
      description: "A delicious burger with lettuce, tomato, and cheese.",
      price: 8.99,
      ingredients: ["Beef Patty", "Lettuce", "Tomato", "Cheese", "Bun"],
    },
    {
      ...menuItem,
      name: "Spaghetti Carbonara",
      description: "Classic Italian pasta with creamy sauce and bacon.",
      price: 12.99,
      ingredients: ["Pasta", "Eggs", "Parmesan", "Bacon", "Cream"],
    },
    {
      ...menuItem,
      name: "Margherita Pizza",
      description:
        "Traditional pizza with fresh tomatoes, mozzarella, and basil.",
      price: 10.99,
      ingredients: ["Pizza Dough", "Tomatoes", "Mozzarella", "Basil"],
    },
    {
      ...menuItem,
      name: "Caesar Salad",
      description: "Crisp romaine lettuce with Caesar dressing and croutons.",
      price: 7.99,
      ingredients: [
        "Romaine Lettuce",
        "Caesar Dressing",
        "Croutons",
        "Parmesan",
      ],
    },
    {
      ...menuItem,
      name: "Grilled Chicken Sandwich",
      description: "Tender grilled chicken with mayo, lettuce, and tomato.",
      price: 9.49,
      ingredients: ["Chicken Breast", "Lettuce", "Tomato", "Mayo", "Bun"],
    },

    {
      ...menuItem,
      name: "BBQ Ribs",
      description: "Slow-cooked ribs with a smoky BBQ sauce.",
      price: 14.99,
      ingredients: ["Pork Ribs", "BBQ Sauce", "Spices"],
    },
    {
      ...menuItem,
      name: "Vegetable Stir Fry",
      description: "A mix of seasonal vegetables sautéed in soy sauce.",
      price: 10.49,
      ingredients: ["Bell Peppers", "Carrots", "Broccoli", "Soy Sauce"],
    },
    {
      ...menuItem,
      name: "Fish Tacos",
      description: "Grilled fish served in soft tortillas with salsa.",
      price: 11.99,
      ingredients: ["Grilled Fish", "Tortillas", "Salsa", "Cabbage"],
    },
    {
      ...menuItem,
      name: "Mushroom Risotto",
      description: "Creamy risotto cooked with fresh mushrooms.",
      price: 13.49,
      ingredients: ["Arborio Rice", "Mushrooms", "Broth", "Parmesan"],
    },
    {
      ...menuItem,
      name: "Chicken Alfredo",
      description: "Pasta in a creamy Alfredo sauce with grilled chicken.",
      price: 12.99,
      ingredients: [
        "Fettuccine",
        "Alfredo Sauce",
        "Grilled Chicken",
        "Parmesan",
      ],
    },
    {
      ...menuItem,
      name: "Lamb Gyro",
      description: "Savory lamb meat served in pita bread with tzatziki.",
      price: 9.99,
      ingredients: ["Lamb", "Pita Bread", "Tzatziki Sauce", "Tomato", "Onion"],
    },
    {
      ...menuItem,
      name: "Cauliflower Wings",
      description: "Crispy cauliflower bites served with ranch dressing.",
      price: 8.49,
      ingredients: ["Cauliflower", "Batter", "Spices", "Ranch Dressing"],
    },
    {
      ...menuItem,
      name: "Buffalo Wings",
      description:
        "Spicy chicken wings served with celery and blue cheese dressing.",
      price: 9.99,
      ingredients: [
        "Chicken Wings",
        "Hot Sauce",
        "Celery",
        "Blue Cheese Dressing",
      ],
    },
    {
      ...menuItem,
      name: "Fettuccine Alfredo",
      description: "Creamy fettuccine pasta tossed in Alfredo sauce.",
      price: 11.49,
      ingredients: ["Fettuccine", "Alfredo Sauce", "Parmesan", "Butter"],
    },
    {
      ...menuItem,
      name: "Caprese Salad",
      description:
        "Fresh mozzarella, tomatoes, and basil drizzled with balsamic glaze.",
      price: 8.49,
      ingredients: ["Mozzarella", "Tomatoes", "Basil", "Balsamic Glaze"],
    },
    {
      ...menuItem,
      name: "Vegetable Quesadilla",
      description: "Flour tortilla filled with cheese and mixed vegetables.",
      price: 8.99,
      ingredients: [
        "Flour Tortilla",
        "Cheese",
        "Bell Peppers",
        "Onions",
        "Zucchini",
      ],
    },
    {
      ...menuItem,
      name: "Pesto Pasta",
      description: "Pasta tossed in a flavorful basil pesto sauce.",
      price: 10.49,
      ingredients: ["Pasta", "Basil Pesto", "Parmesan", "Olive Oil"],
    },
    {
      ...menuItem,
      name: "Beef Tacos",
      description: "Soft tacos filled with seasoned beef, lettuce, and cheese.",
      price: 9.49,
      ingredients: ["Ground Beef", "Tortillas", "Lettuce", "Cheese"],
    },
    {
      ...menuItem,
      name: "Eggplant Parmesan",
      description:
        "Breaded eggplant slices baked with marinara sauce and cheese.",
      price: 11.99,
      ingredients: [
        "Eggplant",
        "Marinara Sauce",
        "Mozzarella",
        "Parmesan",
        "Breadcrumbs",
      ],
    },
    {
      ...menuItem,
      name: "Shrimp Fried Rice",
      description: "Stir-fried rice with shrimp, vegetables, and soy sauce.",
      price: 10.99,
      ingredients: ["Shrimp", "Rice", "Vegetables", "Soy Sauce"],
    },
    {
      ...menuItem,
      name: "Stuffed Bell Peppers",
      description: "Bell peppers stuffed with rice, ground meat, and spices.",
      price: 10.49,
      ingredients: ["Bell Peppers", "Rice", "Ground Meat", "Spices"],
    },
    {
      ...menuItem,
      name: "Quinoa Salad",
      description:
        "Nutritious quinoa mixed with vegetables and a light dressing.",
      price: 9.49,
      ingredients: ["Quinoa", "Cucumber", "Tomatoes", "Lemon Dressing"],
    },
  ],
  drinks: [
    {
      ...menuItem,
      name: "Iced Coffee",
      description: "Refreshing iced coffee served with milk and sugar.",
      price: 3.99,
      ingredients: ["Coffee", "Ice", "Milk", "Sugar"],
    },
    {
      ...menuItem,
      name: "Lemonade",
      description: "Freshly squeezed lemonade with a hint of mint.",
      price: 2.99,
      ingredients: ["Lemons", "Water", "Sugar", "Mint"],
    },
    {
      ...menuItem,
      name: "Coca-Cola",
      description: "Classic carbonated soft drink.",
      price: 1.99,
      ingredients: [
        "Carbonated Water",
        "High Fructose Corn Syrup",
        "Caramel Color",
        "Caffeine",
      ],
    },
    {
      ...menuItem,
      name: "Iced Tea",
      description: "Chilled brewed tea served with lemon.",
      price: 2.49,
      ingredients: ["Tea Leaves", "Water", "Lemon", "Sugar"],
    },
    {
      ...menuItem,
      name: "Milkshake",
      description: "Thick and creamy milkshake available in various flavors.",
      price: 4.99,
      ingredients: ["Ice Cream", "Milk", "Flavoring", "Whipped Cream"],
    },
    {
      ...menuItem,
      name: "Sparkling Water",
      description: "Refreshing sparkling water with a hint of lime.",
      price: 1.49,
      ingredients: ["Carbonated Water", "Lime Juice"],
    },
    {
      ...menuItem,
      name: "Mojito",
      description: "Refreshing cocktail made with rum, mint, lime, and soda.",
      price: 8.99,
      ingredients: ["Rum", "Mint", "Lime Juice", "Soda Water", "Sugar"],
    },
    {
      ...menuItem,
      name: "Pina Colada",
      description: "Tropical blend of rum, coconut cream, and pineapple juice.",
      price: 9.49,
      ingredients: ["Rum", "Coconut Cream", "Pineapple Juice", "Ice"],
    },
    {
      ...menuItem,
      name: "Gin and Tonic",
      description:
        "Classic cocktail made with gin and tonic water, garnished with lime.",
      price: 7.99,
      ingredients: ["Gin", "Tonic Water", "Lime"],
    },
    {
      ...menuItem,
      name: "Cosmopolitan",
      description:
        "A stylish cocktail with vodka, triple sec, cranberry juice, and lime.",
      price: 9.99,
      ingredients: ["Vodka", "Triple Sec", "Cranberry Juice", "Lime Juice"],
    },
    {
      ...menuItem,
      name: "Old Fashioned",
      description:
        "A classic whiskey cocktail with bitters and a hint of orange.",
      price: 10.99,
      ingredients: ["Bourbon", "Bitters", "Sugar", "Orange Slice"],
    },
    {
      ...menuItem,
      name: "Strawberry Daiquiri",
      description: "Frozen cocktail with strawberries, rum, and lime juice.",
      price: 8.49,
      ingredients: ["Rum", "Strawberries", "Lime Juice", "Sugar"],
    },
    {
      ...menuItem,
      name: "Berry Smoothie",
      description: "A blend of mixed berries, yogurt, and honey.",
      price: 5.99,
      ingredients: ["Mixed Berries", "Yogurt", "Honey", "Ice"],
    },
    {
      ...menuItem,
      name: "Matcha Latte",
      description: "Creamy latte made with matcha green tea and steamed milk.",
      price: 4.99,
      ingredients: ["Matcha Powder", "Milk", "Sugar"],
    },
    {
      ...menuItem,
      name: "Bloody Mary",
      description:
        "Spicy cocktail made with vodka, tomato juice, and various spices.",
      price: 9.99,
      ingredients: [
        "Vodka",
        "Tomato Juice",
        "Hot Sauce",
        "Worcestershire Sauce",
        "Lemon Juice",
      ],
    },
    {
      ...menuItem,
      name: "Sparkling Sangria",
      description: "Refreshing wine cocktail with fruits and sparkling water.",
      price: 8.49,
      ingredients: ["Red Wine", "Fruits", "Sparkling Water", "Sugar"],
    },
  ],
  desserts: [
    {
      ...menuItem,
      name: "Cheesecake",
      description: "Creamy cheesecake with a graham cracker crust.",
      price: 4.49,
      ingredients: ["Cream Cheese", "Graham Cracker", "Sugar", "Eggs"],
    },
    {
      ...menuItem,
      name: "Brownie",
      description: "Rich chocolate brownie served warm with vanilla ice cream.",
      price: 3.99,
      ingredients: ["Chocolate", "Flour", "Sugar", "Butter", "Eggs"],
    },
    {
      ...menuItem,
      name: "Fruit Tart",
      description: "Fresh fruit tart with a buttery crust and pastry cream.",
      price: 5.49,
      ingredients: ["Pastry Crust", "Pastry Cream", "Fresh Fruit", "Gelatin"],
    },
    {
      ...menuItem,
      name: "Tiramisu",
      description:
        "Classic Italian dessert made with coffee-soaked ladyfingers.",
      price: 5.99,
      ingredients: ["Mascarpone", "Coffee", "Ladyfingers", "Cocoa Powder"],
    },
    {
      ...menuItem,
      name: "Ice Cream Sundae",
      description: "Delicious ice cream topped with hot fudge and nuts.",
      price: 4.99,
      ingredients: ["Ice Cream", "Hot Fudge", "Nuts", "Whipped Cream"],
    },
    {
      ...menuItem,
      name: "Pancakes",
      description: "Fluffy pancakes served with syrup and butter.",
      price: 6.99,
      ingredients: ["Flour", "Eggs", "Milk", "Syrup", "Butter"],
    },
    {
      ...menuItem,
      name: "Chocolate Cake",
      description: "Rich chocolate cake topped with chocolate frosting.",
      price: 5.99,
      ingredients: ["Flour", "Cocoa Powder", "Sugar", "Eggs", "Frosting"],
    },
    {
      ...menuItem,
      name: "Chocolate Mousse",
      description: "Light and airy chocolate mousse topped with whipped cream.",
      price: 5.99,
      ingredients: ["Dark Chocolate", "Eggs", "Cream", "Sugar"],
    },
    {
      ...menuItem,
      name: "Carrot Cake",
      description: "Moist carrot cake with cream cheese frosting.",
      price: 6.49,
      ingredients: ["Carrots", "Flour", "Sugar", "Eggs", "Cream Cheese"],
    },
    {
      ...menuItem,
      name: "Apple Pie",
      description: "Classic apple pie with a flaky crust and cinnamon.",
      price: 4.99,
      ingredients: ["Apples", "Flour", "Sugar", "Butter", "Cinnamon"],
    },
    {
      ...menuItem,
      name: "Pavlova",
      description:
        "Crispy meringue dessert topped with fresh fruits and whipped cream.",
      price: 6.99,
      ingredients: ["Egg Whites", "Sugar", "Whipped Cream", "Fruits"],
    },
    {
      ...menuItem,
      name: "Key Lime Pie",
      description: "Tangy key lime pie with a graham cracker crust.",
      price: 5.49,
      ingredients: [
        "Key Lime Juice",
        "Sweetened Condensed Milk",
        "Eggs",
        "Graham Cracker Crust",
      ],
    },
    {
      ...menuItem,
      name: "Chocolate Mousse",
      description: "Light and airy chocolate mousse topped with whipped cream.",
      price: 5.99,
      ingredients: ["Dark Chocolate", "Eggs", "Cream", "Sugar"],
    },
    {
      ...menuItem,
      name: "Carrot Cake",
      description: "Moist carrot cake with cream cheese frosting.",
      price: 6.49,
      ingredients: ["Carrots", "Flour", "Sugar", "Eggs", "Cream Cheese"],
    },
    {
      ...menuItem,
      name: "Apple Pie",
      description: "Classic apple pie with a flaky crust and cinnamon.",
      price: 4.99,
      ingredients: ["Apples", "Flour", "Sugar", "Butter", "Cinnamon"],
    },
    {
      ...menuItem,
      name: "Pavlova",
      description:
        "Crispy meringue dessert topped with fresh fruits and whipped cream.",
      price: 6.99,
      ingredients: ["Egg Whites", "Sugar", "Whipped Cream", "Fruits"],
    },
    {
      ...menuItem,
      name: "Key Lime Pie",
      description: "Tangy key lime pie with a graham cracker crust.",
      price: 5.49,
      ingredients: [
        "Key Lime Juice",
        "Sweetened Condensed Milk",
        "Eggs",
        "Graham Cracker Crust",
      ],
    },
  ],
};
