export const foodData = {
  "meal-data": [
    {
      id: 1,
      name: "Brisket",
      serving_size: "100g",
      calories_per_serving: 250,
      protein_per_serving: "20g",
      fat_per_serving: "18g",
    },
    {
      id: 2,
      name: "Apple",
      serving_size: "1 medium (182g)",
      calories_per_serving: 95,
      protein_per_serving: "0.5g",
      fat_per_serving: "0.3g",
    },
    {
      id: 3,
      name: "Hamburger",
      serving_size: "1 sandwich (100g)",
      calories_per_serving: 250,
      protein_per_serving: "12g",
      fat_per_serving: "10g",
    },
    {
      id: 4,
      name: "Salmon",
      serving_size: "100g",
      calories_per_serving: 208,
      protein_per_serving: "20g",
      fat_per_serving: "13g",
    },
    {
      id: 5,
      name: "Broccoli",
      serving_size: "1 cup (91g)",
      calories_per_serving: 31,
      protein_per_serving: "2.5g",
      fat_per_serving: "0.3g",
    },
    {
      id: 6,
      name: "Almonds",
      serving_size: "1 oz (28g)",
      calories_per_serving: 164,
      protein_per_serving: "6g",
      fat_per_serving: "14g",
    },
    {
      id: 7,
      name: "Chicken Breast",
      serving_size: "100g",
      calories_per_serving: 165,
      protein_per_serving: "31g",
      fat_per_serving: "3.6g",
    },
    {
      id: 8,
      name: "Banana",
      serving_size: "1 medium (118g)",
      calories_per_serving: 105,
      protein_per_serving: "1.3g",
      fat_per_serving: "0.3g",
    },
    {
      id: 9,
      name: "Avocado",
      serving_size: "1 medium (150g)",
      calories_per_serving: 240,
      protein_per_serving: "3g",
      fat_per_serving: "22g",
    },
    {
      id: 10,
      name: "Oatmeal",
      serving_size: "1 cup (234g)",
      calories_per_serving: 154,
      protein_per_serving: "6g",
      fat_per_serving: "3g",
    },
    {
      id: 11,
      name: "Greek Yogurt",
      serving_size: "1 cup (245g)",
      calories_per_serving: 149,
      protein_per_serving: "10g",
      fat_per_serving: "4g",
    },
    {
      id: 12,
      name: "Blueberries",
      serving_size: "1 cup (148g)",
      calories_per_serving: 84,
      protein_per_serving: "1g",
      fat_per_serving: "0.5g",
    },
    {
      id: 13,
      name: "Scrambled Eggs",
      serving_size: "2 large eggs (100g)",
      calories_per_serving: 140,
      protein_per_serving: "12g",
      fat_per_serving: "10g",
    },
    {
      id: 14,
      name: "Whole Grain Toast",
      serving_size: "1 slice (28g)",
      calories_per_serving: 69,
      protein_per_serving: "3.6g",
      fat_per_serving: "1.1g",
    },
    {
      id: 15,
      name: "Quinoa Salad",
      serving_size: "1 cup (185g)",
      calories_per_serving: 222,
      protein_per_serving: "8g",
      fat_per_serving: "3.6g",
    },
    {
      id: 16,
      name: "Grilled Chicken Breast",
      serving_size: "100g",
      calories_per_serving: 165,
      protein_per_serving: "31g",
      fat_per_serving: "3.6g",
    },
    {
      id: 17,
      name: "Brown Rice",
      serving_size: "1 cup (195g)",
      calories_per_serving: 216,
      protein_per_serving: "5g",
      fat_per_serving: "1.8g",
    },
    {
      id: 18,
      name: "Steamed Broccoli",
      serving_size: "1 cup (156g)",
      calories_per_serving: 55,
      protein_per_serving: "3.7g",
      fat_per_serving: "0.6g",
    },
    {
      id: 19,
      name: "Baked Salmon",
      serving_size: "100g",
      calories_per_serving: 208,
      protein_per_serving: "20g",
      fat_per_serving: "13g",
    },
    {
      id: 20,
      name: "Sweet Potato",
      serving_size: "1 medium (130g)",
      calories_per_serving: 112,
      protein_per_serving: "2g",
      fat_per_serving: "0.1g",
    },
    {
      id: 21,
      name: "Hummus",
      serving_size: "2 tbsp (30g)",
      calories_per_serving: 70,
      protein_per_serving: "2g",
      fat_per_serving: "5g",
    },
    {
      id: 22,
      name: "Carrot Sticks",
      serving_size: "1 cup (128g)",
      calories_per_serving: 52,
      protein_per_serving: "1.2g",
      fat_per_serving: "0.3g",
    },
    {
      id: 23,
      name: "Almond Butter",
      serving_size: "2 tbsp (32g)",
      calories_per_serving: 190,
      protein_per_serving: "7g",
      fat_per_serving: "16g",
    },
    {
      id: 24,
      name: "Mixed Nuts",
      serving_size: "1 oz (28g)",
      calories_per_serving: 173,
      protein_per_serving: "5g",
      fat_per_serving: "15g",
    },
    {
      id: 25,
      name: "Cottage Cheese",
      serving_size: "1 cup (210g)",
      calories_per_serving: 206,
      protein_per_serving: "28g",
      fat_per_serving: "9g",
    },
    {
      id: 26,
      name: "Spinach Salad",
      serving_size: "1 cup (30g)",
      calories_per_serving: 7,
      protein_per_serving: "0.9g",
      fat_per_serving: "0.1g",
    },
    {
      id: 27,
      name: "Turkey Sandwich",
      serving_size: "1 sandwich (150g)",
      calories_per_serving: 250,
      protein_per_serving: "18g",
      fat_per_serving: "8g",
    },
    {
      id: 28,
      name: "Lentil Soup",
      serving_size: "1 cup (198g)",
      calories_per_serving: 186,
      protein_per_serving: "12g",
      fat_per_serving: "0.8g",
    },
    {
      id: 29,
      name: "Grilled Shrimp",
      serving_size: "100g",
      calories_per_serving: 99,
      protein_per_serving: "24g",
      fat_per_serving: "0.3g",
    },
    {
      id: 30,
      name: "Mashed Potatoes",
      serving_size: "1 cup (210g)",
      calories_per_serving: 214,
      protein_per_serving: "4g",
      fat_per_serving: "9g",
    },
    {
      id: 31,
      name: "Beef Stir-Fry",
      serving_size: "1 cup (200g)",
      calories_per_serving: 250,
      protein_per_serving: "20g",
      fat_per_serving: "15g",
    },
    {
      id: 32,
      name: "Tofu Stir-Fry",
      serving_size: "1 cup (200g)",
      calories_per_serving: 180,
      protein_per_serving: "15g",
      fat_per_serving: "10g",
    },
    {
      id: 33,
      name: "Pasta Primavera",
      serving_size: "1 cup (200g)",
      calories_per_serving: 220,
      protein_per_serving: "8g",
      fat_per_serving: "7g",
    },
    {
      id: 34,
      name: "Caesar Salad",
      serving_size: "1 cup (100g)",
      calories_per_serving: 190,
      protein_per_serving: "7g",
      fat_per_serving: "15g",
    },
    {
      id: 35,
      name: "Fruit Smoothie",
      serving_size: "1 cup (240ml)",
      calories_per_serving: 150,
      protein_per_serving: "2g",
      fat_per_serving: "1g",
    },
    {
      id: 36,
      name: "Granola Bar",
      serving_size: "1 bar (40g)",
      calories_per_serving: 150,
      protein_per_serving: "3g",
      fat_per_serving: "5g",
    },
    {
      id: 37,
      name: "Peanut Butter",
      serving_size: "2 tbsp (32g)",
      calories_per_serving: 190,
      protein_per_serving: "8g",
      fat_per_serving: "16g",
    },
    {
      id: 38,
      name: "Hard-Boiled Eggs",
      serving_size: "2 large eggs (100g)",
      calories_per_serving: 140,
      protein_per_serving: "12g",
      fat_per_serving: "10g",
    },
    {
      id: 39,
      name: "Edamame",
      serving_size: "1 cup (155g)",
      calories_per_serving: 188,
      protein_per_serving: "17g",
      fat_per_serving: "8g",
    },
    {
      id: 40,
      name: "Dark Chocolate",
      serving_size: "1 oz (28g)",
      calories_per_serving: 155,
      protein_per_serving: "2g",
      fat_per_serving: "9g",
    },
    {
      id: 41,
      name: "Water",
      serving_size: "1 cup (240ml)",
      calories_per_serving: 0,
      protein_per_serving: "0g",
      fat_per_serving: "0g",
    },
    {
      id: 42,
      name: "Orange Juice",
      serving_size: "1 cup (240ml)",
      calories_per_serving: 112,
      protein_per_serving: "1.2g",
      fat_per_serving: "0.5g",
    },
    {
      id: 43,
      name: "Soda",
      serving_size: "1 can (355ml)",
      calories_per_serving: 140,
      protein_per_serving: "0g",
      fat_per_serving: "0g",
    },
    {
      id: 44,
      name: "Coffee",
      serving_size: "1 cup (240ml)",
      calories_per_serving: 2,
      protein_per_serving: "0g",
      fat_per_serving: "0g",
    },
    {
      id: 45,
      name: "Tea",
      serving_size: "1 cup (240ml)",
      calories_per_serving: 2,
      protein_per_serving: "0g",
      fat_per_serving: "0g",
    },
    {
      id: 46,
      name: "Milk",
      serving_size: "1 cup (240ml)",
      calories_per_serving: 103,
      protein_per_serving: "8g",
      fat_per_serving: "5g",
    },
  ],
};
