export const foodData = {
  "meal-data": [
    {
      id: 1,
      name: "Brisket",
      serving_size: "100g",
      calories_per_serving: 250,
      protein_per_serving: 20,
      fat_per_serving: 18,
      carbs_per_serving: 0,
      qty: 1,
    },
    {
      id: 2,
      name: "Apple",
      serving_size: "1 medium (182g)",
      calories_per_serving: 95,
      protein_per_serving: 0.5,
      fat_per_serving: 0.3,
      carbs_per_serving: 0,
      qty: 1,
    },
    {
      id: 3,
      name: "Hamburger",
      serving_size: "1 sandwich (100g)",
      calories_per_serving: 250,
      protein_per_serving: 12,
      fat_per_serving: 10,
      carbs_per_serving: 0,
      qty: 1,
    },
    {
      id: 4,
      name: "Salmon",
      serving_size: "100g",
      calories_per_serving: 208,
      protein_per_serving: 20,
      fat_per_serving: 13,
      carbs_per_serving: 0,
      qty: 1,
    },
    {
      id: 5,
      name: "Broccoli",
      serving_size: "1 cup (91g)",
      calories_per_serving: 31,
      protein_per_serving: 2.5,
      fat_per_serving: 0.3,
      carbs_per_serving: 0,
      qty: 1,
    },
    {
      id: 6,
      name: "Almonds",
      serving_size: "1 oz (28g)",
      calories_per_serving: 164,
      protein_per_serving: 6,
      fat_per_serving: 14,
      carbs_per_serving: 0,
      qty: 1,
    },
    {
      id: 7,
      name: "Chicken Breast",
      serving_size: "100g",
      calories_per_serving: 165,
      protein_per_serving: 31,
      fat_per_serving: 3.6,
      carbs_per_serving: 0,
      qty: 1,
    },
    {
      id: 8,
      name: "Banana",
      serving_size: "1 medium (118g)",
      calories_per_serving: 105,
      protein_per_serving: 1.3,
      fat_per_serving: 0.3,
      carbs_per_serving: 0,
      qty: 1,
    },
    {
      id: 9,
      name: "Avocado",
      serving_size: "1 medium (150g)",
      calories_per_serving: 240,
      protein_per_serving: 3,
      fat_per_serving: 22,
      carbs_per_serving: 0,
      qty: 1,
    },
    {
      id: 10,
      name: "Oatmeal",
      serving_size: "1 cup (234g)",
      calories_per_serving: 154,
      protein_per_serving: 6,
      fat_per_serving: 3,
      carbs_per_serving: 0,
      qty: 1,
    },
    {
      id: 11,
      name: "Pineapple",
      serving_size: "1 cup (165g)",
      calories_per_serving: 82,
      protein_per_serving: 0.9,
      fat_per_serving: 0.2,
      carbs_per_serving: 22,
      qty: 1,
    },
    {
      id: 12,
      name: "Pear",
      serving_size: "1 medium (178g)",
      calories_per_serving: 101,
      protein_per_serving: 0.6,
      fat_per_serving: 0.3,
      carbs_per_serving: 27,
      qty: 1,
    },
    {
      id: 13,
      name: "Orange",
      serving_size: "1 medium (131g)",
      calories_per_serving: 62,
      protein_per_serving: 1.2,
      fat_per_serving: 0.2,
      carbs_per_serving: 15,
      qty: 1,
    },
    {
      id: 14,
      name: "Grapes",
      serving_size: "1 cup (151g)",
      calories_per_serving: 104,
      protein_per_serving: 1.1,
      fat_per_serving: 0.2,
      carbs_per_serving: 27,
      qty: 1,
    },
    {
      id: 15,
      name: "Strawberries",
      serving_size: "1 cup (152g)",
      calories_per_serving: 49,
      protein_per_serving: 1,
      fat_per_serving: 0.5,
      carbs_per_serving: 12,
      qty: 1,
    },
    {
      id: 16,
      name: "Blueberries",
      serving_size: "1 cup (148g)",
      calories_per_serving: 85,
      protein_per_serving: 1.1,
      fat_per_serving: 0.5,
      carbs_per_serving: 21,
      qty: 1,
    },
    {
      id: 17,
      name: "Peach",
      serving_size: "1 medium (150g)",
      calories_per_serving: 58,
      protein_per_serving: 1.4,
      fat_per_serving: 0.4,
      carbs_per_serving: 14,
      qty: 1,
    },
    {
      id: 18,
      name: "Watermelon",
      serving_size: "1 cup (152g)",
      calories_per_serving: 46,
      protein_per_serving: 0.9,
      fat_per_serving: 0.2,
      carbs_per_serving: 12,
      qty: 1,
    },
    {
      id: 19,
      name: "Cucumber",
      serving_size: "1 cup (104g)",
      calories_per_serving: 16,
      protein_per_serving: 0.7,
      fat_per_serving: 0.1,
      carbs_per_serving: 4,
      qty: 1,
    },
    {
      id: 20,
      name: "Lemon",
      serving_size: "1 medium (58g)",
      calories_per_serving: 17,
      protein_per_serving: 0.6,
      fat_per_serving: 0.2,
      carbs_per_serving: 5,
      qty: 1,
    },
    {
      id: 21,
      name: "Cherry",
      serving_size: "1 cup (154g)",
      calories_per_serving: 97,
      protein_per_serving: 2.1,
      fat_per_serving: 0.3,
      carbs_per_serving: 25,
      qty: 1,
    },
    {
      id: 22,
      name: "Mango",
      serving_size: "1 medium (200g)",
      calories_per_serving: 150,
      protein_per_serving: 1.4,
      fat_per_serving: 0.6,
      carbs_per_serving: 35,
      qty: 1,
    },
    {
      id: 23,
      name: "Kiwi",
      serving_size: "1 medium (76g)",
      calories_per_serving: 42,
      protein_per_serving: 0.8,
      fat_per_serving: 0.4,
      carbs_per_serving: 10,
      qty: 1,
    },
    {
      id: 24,
      name: "Papaya",
      serving_size: "1 cup (145g)",
      calories_per_serving: 59,
      protein_per_serving: 0.5,
      fat_per_serving: 0.4,
      carbs_per_serving: 15,
      qty: 1,
    },
    {
      id: 25,
      name: "Coconut",
      serving_size: "1 cup (80g)",
      calories_per_serving: 283,
      protein_per_serving: 2.8,
      fat_per_serving: 27,
      carbs_per_serving: 12,
      qty: 1,
    },
    {
      id: 26,
      name: "Fig",
      serving_size: "1 medium (50g)",
      calories_per_serving: 37,
      protein_per_serving: 0.4,
      fat_per_serving: 0.2,
      carbs_per_serving: 9,
      qty: 1,
    },
    {
      id: 27,
      name: "Date",
      serving_size: "1 medium (24g)",
      calories_per_serving: 66,
      protein_per_serving: 0.5,
      fat_per_serving: 0.2,
      carbs_per_serving: 18,
      qty: 1,
    },
    {
      id: 28,
      name: "Apricot",
      serving_size: "1 medium (35g)",
      calories_per_serving: 17,
      protein_per_serving: 0.5,
      fat_per_serving: 0.1,
      carbs_per_serving: 4,
      qty: 1,
    },
    {
      id: 29,
      name: "Nectarine",
      serving_size: "1 medium (150g)",
      calories_per_serving: 63,
      protein_per_serving: 1.5,
      fat_per_serving: 0.3,
      carbs_per_serving: 15,
      qty: 1,
    },
    {
      id: 30,
      name: "Passion Fruit",
      serving_size: "1 medium (18g)",
      calories_per_serving: 17,
      protein_per_serving: 0.4,
      fat_per_serving: 0.1,
      carbs_per_serving: 4,
      qty: 1,
    },
    {
      id: 31,
      name: "Plum",
      serving_size: "1 medium (66g)",
      calories_per_serving: 30,
      protein_per_serving: 0.5,
      fat_per_serving: 0.2,
      carbs_per_serving: 8,
      qty: 1,
    },
    {
      id: 32,
      name: "Blackcurrant",
      serving_size: "1 cup (112g)",
      calories_per_serving: 63,
      protein_per_serving: 1.5,
      fat_per_serving: 0.3,
      carbs_per_serving: 14,
      qty: 1,
    },
    {
      id: 33,
      name: "Grapefruit",
      serving_size: "1 medium (236g)",
      calories_per_serving: 82,
      protein_per_serving: 1.8,
      fat_per_serving: 0.2,
      carbs_per_serving: 20,
      qty: 1,
    },
    {
      id: 34,
      name: "Lime",
      serving_size: "1 medium (67g)",
      calories_per_serving: 20,
      protein_per_serving: 0.5,
      fat_per_serving: 0.1,
      carbs_per_serving: 7,
      qty: 1,
    },
    {
      id: 35,
      name: "Tangerine",
      serving_size: "1 medium (88g)",
      calories_per_serving: 47,
      protein_per_serving: 0.9,
      fat_per_serving: 0.2,
      carbs_per_serving: 12,
      qty: 1,
    },
    {
      id: 36,
      name: "Carrot",
      serving_size: "1 medium (61g)",
      calories_per_serving: 25,
      protein_per_serving: 0.6,
      fat_per_serving: 0.1,
      carbs_per_serving: 6,
      qty: 1,
    },
    {
      id: 37,
      name: "Sweet Potato",
      serving_size: "1 medium (114g)",
      calories_per_serving: 103,
      protein_per_serving: 2.3,
      fat_per_serving: 0.2,
      carbs_per_serving: 24,
      qty: 1,
    },
    {
      id: 38,
      name: "Pumpkin",
      serving_size: "1 cup (245g)",
      calories_per_serving: 49,
      protein_per_serving: 2,
      fat_per_serving: 0.2,
      carbs_per_serving: 12,
      qty: 1,
    },
    {
      id: 39,
      name: "Cauliflower",
      serving_size: "1 cup (100g)",
      calories_per_serving: 25,
      protein_per_serving: 1.9,
      fat_per_serving: 0.3,
      carbs_per_serving: 5,
      qty: 1,
    },
    {
      id: 40,
      name: "Spinach",
      serving_size: "1 cup (30g)",
      calories_per_serving: 7,
      protein_per_serving: 0.9,
      fat_per_serving: 0.1,
      carbs_per_serving: 1,
      qty: 1,
    },
    {
      id: 41,
      name: "Kale",
      serving_size: "1 cup (67g)",
      calories_per_serving: 33,
      protein_per_serving: 2.9,
      fat_per_serving: 0.5,
      carbs_per_serving: 7,
      qty: 1,
    },
    {
      id: 42,
      name: "Cauliflower",
      serving_size: "1 cup (107g)",
      calories_per_serving: 25,
      protein_per_serving: 2,
      fat_per_serving: 0.3,
      carbs_per_serving: 5,
      qty: 1,
    },
    {
      id: 43,
      name: "Bell Pepper",
      serving_size: "1 medium (119g)",
      calories_per_serving: 24,
      protein_per_serving: 1,
      fat_per_serving: 0.2,
      carbs_per_serving: 6,
      qty: 1,
    },
    {
      id: 44,
      name: "Zucchini",
      serving_size: "1 medium (196g)",
      calories_per_serving: 33,
      protein_per_serving: 2.4,
      fat_per_serving: 0.6,
      carbs_per_serving: 7,
      qty: 1,
    },
    {
      id: 45,
      name: "Cucumber",
      serving_size: "1 medium (301g)",
      calories_per_serving: 45,
      protein_per_serving: 2,
      fat_per_serving: 0.3,
      carbs_per_serving: 11,
      qty: 1,
    },
    {
      id: 46,
      name: "Asparagus",
      serving_size: "1 cup (134g)",
      calories_per_serving: 27,
      protein_per_serving: 3,
      fat_per_serving: 0.2,
      carbs_per_serving: 5,
      qty: 1,
    },
    {
      id: 47,
      name: "Brussels Sprouts",
      serving_size: "1 cup (156g)",
      calories_per_serving: 38,
      protein_per_serving: 3,
      fat_per_serving: 0.3,
      carbs_per_serving: 8,
      qty: 1,
    },
    {
      id: 48,
      name: "Artichoke",
      serving_size: "1 medium (120g)",
      calories_per_serving: 60,
      protein_per_serving: 4.2,
      fat_per_serving: 0.2,
      carbs_per_serving: 14,
      qty: 1,
    },
    {
      id: 49,
      name: "Green Beans",
      serving_size: "1 cup (125g)",
      calories_per_serving: 44,
      protein_per_serving: 2,
      fat_per_serving: 0.2,
      carbs_per_serving: 10,
      qty: 1,
    },
    {
      id: 50,
      name: "Peas",
      serving_size: "1 cup (160g)",
      calories_per_serving: 62,
      protein_per_serving: 4.2,
      fat_per_serving: 0.4,
      carbs_per_serving: 11,
      qty: 1,
    },
    {
      id: 51,
      name: "Chicken Burrito",
      serving_size: "1 burrito (250g)",
      calories_per_serving: 550,
      protein_per_serving: 35,
      fat_per_serving: 22,
      carbs_per_serving: 55,
      qty: 1,
    },
    {
      id: 52,
      name: "Beef Taco",
      serving_size: "1 taco (120g)",
      calories_per_serving: 226,
      protein_per_serving: 12,
      fat_per_serving: 13,
      carbs_per_serving: 18,
      qty: 1,
    },
    {
      id: 53,
      name: "Spaghetti Bolognese",
      serving_size: "1 plate (300g)",
      calories_per_serving: 450,
      protein_per_serving: 20,
      fat_per_serving: 15,
      carbs_per_serving: 60,
      qty: 1,
    },
    {
      id: 54,
      name: "Pad Thai",
      serving_size: "1 plate (400g)",
      calories_per_serving: 600,
      protein_per_serving: 26,
      fat_per_serving: 20,
      carbs_per_serving: 85,
      qty: 1,
    },
    {
      id: 55,
      name: "Cheeseburger",
      serving_size: "1 burger (150g)",
      calories_per_serving: 300,
      protein_per_serving: 16,
      fat_per_serving: 18,
      carbs_per_serving: 27,
      qty: 1,
    },
    {
      id: 56,
      name: "Pepperoni Pizza",
      serving_size: "1 slice (120g)",
      calories_per_serving: 285,
      protein_per_serving: 12,
      fat_per_serving: 10,
      carbs_per_serving: 36,
      qty: 1,
    },
    {
      id: 57,
      name: "Beef Burrito Bowl",
      serving_size: "1 bowl (300g)",
      calories_per_serving: 600,
      protein_per_serving: 35,
      fat_per_serving: 20,
      carbs_per_serving: 65,
      qty: 1,
    },
    {
      id: 58,
      name: "Shrimp Fried Rice",
      serving_size: "1 plate (350g)",
      calories_per_serving: 500,
      protein_per_serving: 22,
      fat_per_serving: 16,
      carbs_per_serving: 70,
      qty: 1,
    },
    {
      id: 59,
      name: "Lasagna",
      serving_size: "1 piece (250g)",
      calories_per_serving: 420,
      protein_per_serving: 21,
      fat_per_serving: 24,
      carbs_per_serving: 30,
      qty: 1,
    },
    {
      id: 60,
      name: "Ramen Noodles",
      serving_size: "1 bowl (400g)",
      calories_per_serving: 450,
      protein_per_serving: 12,
      fat_per_serving: 14,
      carbs_per_serving: 60,
      qty: 1,
    },
  ],
};
