export const foodData = {
  "meal-data": [
    {
      id: 1,
      name: "Brisket",
      serving_size: "100g",
      calories_per_serving: 250,
      protein_per_serving: 20,
      fat_per_serving: 18,
      carbs_per_serving: 0,
    },
    {
      id: 2,
      name: "Apple",
      serving_size: "1 medium (182g)",
      calories_per_serving: 95,
      protein_per_serving: 0.5,
      fat_per_serving: 0.3,
      carbs_per_serving: 0,
    },
    {
      id: 3,
      name: "Hamburger",
      serving_size: "1 sandwich (100g)",
      calories_per_serving: 250,
      protein_per_serving: 12,
      fat_per_serving: 10,
      carbs_per_serving: 0,
    },
    {
      id: 4,
      name: "Salmon",
      serving_size: "100g",
      calories_per_serving: 208,
      protein_per_serving: 20,
      fat_per_serving: 13,
      carbs_per_serving: 0,
    },
    {
      id: 5,
      name: "Broccoli",
      serving_size: "1 cup (91g)",
      calories_per_serving: 31,
      protein_per_serving: 2.5,
      fat_per_serving: 0.3,
      carbs_per_serving: 0,
    },
    {
      id: 6,
      name: "Almonds",
      serving_size: "1 oz (28g)",
      calories_per_serving: 164,
      protein_per_serving: 6,
      fat_per_serving: 14,
      carbs_per_serving: 0,
    },
    {
      id: 7,
      name: "Chicken Breast",
      serving_size: "100g",
      calories_per_serving: 165,
      protein_per_serving: 31,
      fat_per_serving: 3.6,
      carbs_per_serving: 0,
    },
    {
      id: 8,
      name: "Banana",
      serving_size: "1 medium (118g)",
      calories_per_serving: 105,
      protein_per_serving: 1.3,
      fat_per_serving: 0.3,
      carbs_per_serving: 0,
    },
    {
      id: 9,
      name: "Avocado",
      serving_size: "1 medium (150g)",
      calories_per_serving: 240,
      protein_per_serving: 3,
      fat_per_serving: 22,
      carbs_per_serving: 0,
    },
    {
      id: 10,
      name: "Oatmeal",
      serving_size: "1 cup (234g)",
      calories_per_serving: 154,
      protein_per_serving: 6,
      fat_per_serving: 3,
      carbs_per_serving: 0,
    },
    {
      id: 11,
      name: "Banana",
      serving_size: "1 medium (118g)",
      calories_per_serving: 105,
      protein_per_serving: 1.3,
      fat_per_serving: 0.3,
      carbs_per_serving: 27,
    },
    {
      id: 12,
      name: "Apple",
      serving_size: "1 medium (182g)",
      calories_per_serving: 95,
      protein_per_serving: 0.5,
      fat_per_serving: 0.3,
      carbs_per_serving: 25,
    },
    {
      id: 13,
      name: "Orange",
      serving_size: "1 medium (131g)",
      calories_per_serving: 62,
      protein_per_serving: 1.2,
      fat_per_serving: 0.2,
      carbs_per_serving: 15,
    },
    {
      id: 14,
      name: "Grapes",
      serving_size: "1 cup (151g)",
      calories_per_serving: 104,
      protein_per_serving: 1.1,
      fat_per_serving: 0.2,
      carbs_per_serving: 27,
    },
    {
      id: 15,
      name: "Strawberries",
      serving_size: "1 cup (152g)",
      calories_per_serving: 49,
      protein_per_serving: 1,
      fat_per_serving: 0.5,
      carbs_per_serving: 12,
    },
    {
      id: 16,
      name: "Blueberries",
      serving_size: "1 cup (148g)",
      calories_per_serving: 85,
      protein_per_serving: 1.1,
      fat_per_serving: 0.5,
      carbs_per_serving: 21,
    },
    {
      id: 17,
      name: "Peach",
      serving_size: "1 medium (150g)",
      calories_per_serving: 58,
      protein_per_serving: 1.4,
      fat_per_serving: 0.4,
      carbs_per_serving: 14,
    },
    {
      id: 18,
      name: "Watermelon",
      serving_size: "1 cup (152g)",
      calories_per_serving: 46,
      protein_per_serving: 0.9,
      fat_per_serving: 0.2,
      carbs_per_serving: 12,
    },
    {
      id: 19,
      name: "Avocado",
      serving_size: "1 medium (150g)",
      calories_per_serving: 240,
      protein_per_serving: 3,
      fat_per_serving: 22,
      carbs_per_serving: 12,
    },
    {
      id: 20,
      name: "Lemon",
      serving_size: "1 medium (58g)",
      calories_per_serving: 17,
      protein_per_serving: 0.6,
      fat_per_serving: 0.2,
      carbs_per_serving: 5,
    },
    {
      id: 21,
      name: "Cherry",
      serving_size: "1 cup (154g)",
      calories_per_serving: 97,
      protein_per_serving: 2.1,
      fat_per_serving: 0.3,
      carbs_per_serving: 25,
    },
    {
      id: 22,
      name: "Mango",
      serving_size: "1 medium (200g)",
      calories_per_serving: 150,
      protein_per_serving: 1.4,
      fat_per_serving: 0.6,
      carbs_per_serving: 35,
    },
    {
      id: 23,
      name: "Kiwi",
      serving_size: "1 medium (76g)",
      calories_per_serving: 42,
      protein_per_serving: 0.8,
      fat_per_serving: 0.4,
      carbs_per_serving: 10,
    },
    {
      id: 24,
      name: "Papaya",
      serving_size: "1 cup (145g)",
      calories_per_serving: 59,
      protein_per_serving: 0.5,
      fat_per_serving: 0.4,
      carbs_per_serving: 15,
    },
    {
      id: 25,
      name: "Coconut",
      serving_size: "1 cup (80g)",
      calories_per_serving: 283,
      protein_per_serving: 2.8,
      fat_per_serving: 27,
      carbs_per_serving: 12,
    },
    {
      id: 26,
      name: "Fig",
      serving_size: "1 medium (50g)",
      calories_per_serving: 37,
      protein_per_serving: 0.4,
      fat_per_serving: 0.2,
      carbs_per_serving: 9,
    },
    {
      id: 27,
      name: "Date",
      serving_size: "1 medium (24g)",
      calories_per_serving: 66,
      protein_per_serving: 0.5,
      fat_per_serving: 0.2,
      carbs_per_serving: 18,
    },
    {
      id: 28,
      name: "Apricot",
      serving_size: "1 medium (35g)",
      calories_per_serving: 17,
      protein_per_serving: 0.5,
      fat_per_serving: 0.1,
      carbs_per_serving: 4,
    },
    {
      id: 29,
      name: "Nectarine",
      serving_size: "1 medium (150g)",
      calories_per_serving: 63,
      protein_per_serving: 1.5,
      fat_per_serving: 0.3,
      carbs_per_serving: 15,
    },
    {
      id: 30,
      name: "Passion Fruit",
      serving_size: "1 medium (18g)",
      calories_per_serving: 17,
      protein_per_serving: 0.4,
      fat_per_serving: 0.1,
      carbs_per_serving: 4,
    },
    {
      id: 31,
      name: "Plum",
      serving_size: "1 medium (66g)",
      calories_per_serving: 30,
      protein_per_serving: 0.5,
      fat_per_serving: 0.2,
      carbs_per_serving: 8,
    },
    {
      id: 32,
      name: "Blackcurrant",
      serving_size: "1 cup (112g)",
      calories_per_serving: 63,
      protein_per_serving: 1.5,
      fat_per_serving: 0.3,
      carbs_per_serving: 14,
    },
    {
      id: 33,
      name: "Grapefruit",
      serving_size: "1 medium (236g)",
      calories_per_serving: 82,
      protein_per_serving: 1.8,
      fat_per_serving: 0.2,
      carbs_per_serving: 20,
    },
    {
      id: 34,
      name: "Lime",
      serving_size: "1 medium (67g)",
      calories_per_serving: 20,
      protein_per_serving: 0.5,
      fat_per_serving: 0.1,
      carbs_per_serving: 7,
    },
    {
      id: 35,
      name: "Tangerine",
      serving_size: "1 medium (88g)",
      calories_per_serving: 47,
      protein_per_serving: 0.9,
      fat_per_serving: 0.2,
      carbs_per_serving: 12,
    },
    {
      id: 36,
      name: "Carrot",
      serving_size: "1 medium (61g)",
      calories_per_serving: 25,
      protein_per_serving: 0.6,
      fat_per_serving: 0.1,
      carbs_per_serving: 6,
    },
    {
      id: 37,
      name: "Sweet Potato",
      serving_size: "1 medium (114g)",
      calories_per_serving: 103,
      protein_per_serving: 2.3,
      fat_per_serving: 0.2,
      carbs_per_serving: 24,
    },
    {
      id: 38,
      name: "Pumpkin",
      serving_size: "1 cup (245g)",
      calories_per_serving: 49,
      protein_per_serving: 2,
      fat_per_serving: 0.2,
      carbs_per_serving: 12,
    },
    {
      id: 39,
      name: "Broccoli",
      serving_size: "1 cup (91g)",
      calories_per_serving: 55,
      protein_per_serving: 4,
      fat_per_serving: 0.6,
      carbs_per_serving: 11,
    },
    {
      id: 40,
      name: "Spinach",
      serving_size: "1 cup (30g)",
      calories_per_serving: 7,
      protein_per_serving: 0.9,
      fat_per_serving: 0.1,
      carbs_per_serving: 1,
    },
    {
      id: 41,
      name: "Kale",
      serving_size: "1 cup (67g)",
      calories_per_serving: 33,
      protein_per_serving: 2.9,
      fat_per_serving: 0.5,
      carbs_per_serving: 7,
    },
    {
      id: 42,
      name: "Cauliflower",
      serving_size: "1 cup (107g)",
      calories_per_serving: 25,
      protein_per_serving: 2,
      fat_per_serving: 0.3,
      carbs_per_serving: 5,
    },
    {
      id: 43,
      name: "Bell Pepper",
      serving_size: "1 medium (119g)",
      calories_per_serving: 24,
      protein_per_serving: 1,
      fat_per_serving: 0.2,
      carbs_per_serving: 6,
    },
    {
      id: 44,
      name: "Zucchini",
      serving_size: "1 medium (196g)",
      calories_per_serving: 33,
      protein_per_serving: 2.4,
      fat_per_serving: 0.6,
      carbs_per_serving: 7,
    },
    {
      id: 45,
      name: "Cucumber",
      serving_size: "1 medium (301g)",
      calories_per_serving: 45,
      protein_per_serving: 2,
      fat_per_serving: 0.3,
      carbs_per_serving: 11,
    },
    {
      id: 46,
      name: "Asparagus",
      serving_size: "1 cup (134g)",
      calories_per_serving: 27,
      protein_per_serving: 3,
      fat_per_serving: 0.2,
      carbs_per_serving: 5,
    },
    {
      id: 47,
      name: "Brussels Sprouts",
      serving_size: "1 cup (156g)",
      calories_per_serving: 38,
      protein_per_serving: 3,
      fat_per_serving: 0.3,
      carbs_per_serving: 8,
    },
    {
      id: 48,
      name: "Artichoke",
      serving_size: "1 medium (120g)",
      calories_per_serving: 60,
      protein_per_serving: 4.2,
      fat_per_serving: 0.2,
      carbs_per_serving: 14,
    },
    {
      id: 49,
      name: "Green Beans",
      serving_size: "1 cup (125g)",
      calories_per_serving: 44,
      protein_per_serving: 2,
      fat_per_serving: 0.2,
      carbs_per_serving: 10,
    },
    {
      id: 50,
      name: "Peas",
      serving_size: "1 cup (160g)",
      calories_per_serving: 62,
      protein_per_serving: 4.2,
      fat_per_serving: 0.4,
      carbs_per_serving: 11,
    },
  ],
};
